"""Build the real-PRISM center-pixel synchrony visual walkthrough.

The detailed pair audit uses an observed 91-label PRISM cube spanning the
inclusive interval ``end - 90 days`` through ``end``.  The spatial and temporal
pages use the existing full-record synchrony product generated by
``examples/real_prism_median_split_synchrony.py``.

Run from the repository root::

    python examples/center_pixel_synchrony_walkthrough.py

Use ``--pages-only`` and ``--compose-only`` when figure-generation and PDF
dependencies live in different Python environments.
"""

from __future__ import annotations

import argparse
from datetime import date
import importlib.metadata
import json
import math
from pathlib import Path
import platform
import subprocess
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "artifacts" / "center-pixel-synchrony-walkthrough"
DEFAULT_PAIR_INPUT = (
    DEFAULT_OUTPUT
    / "intermediate"
    / "prism_boulder_2023-11-01_2024-01-30.nc"
)
DEFAULT_FULL_SYNC = REPO_ROOT / "artifacts" / "prism-full-record" / "real_prism_synchrony.nc"
DEFAULT_FULL_MANIFEST = (
    REPO_ROOT / "artifacts" / "prism-full-record" / "real_prism_manifest.json"
)

WINDOW_DAYS = 90
OUTPUT_STRIDE = 30
MIN_T = 10
SPLIT_QUANTILE = 0.5
SNAPSHOT_TARGET = "2024-01-16"
FOCAL_COORD = (39.875, -105.75)

PAGE_WIDTH = 13.333
PAGE_HEIGHT = 7.5
DPI = 180

INK = "#183044"
MUTED = "#607483"
PAPER = "#F7F5EF"
WHITE = "#FFFFFF"
COLD = "#2166AC"
WARM = "#D6604D"
DIFF = "#7B3294"
CENTER = "#F2B134"
FOCAL = "#B23A67"
GRID = "#D8DED9"


def _heavy_imports():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.dates as mdates
    import matplotlib.pyplot as plt
    from matplotlib.colors import TwoSlopeNorm
    from matplotlib.patches import FancyBboxPatch, Rectangle
    import numpy as np
    import pandas as pd
    from scipy.stats import rankdata
    import xarray as xr

    return {
        "mdates": mdates,
        "plt": plt,
        "TwoSlopeNorm": TwoSlopeNorm,
        "FancyBboxPatch": FancyBboxPatch,
        "Rectangle": Rectangle,
        "np": np,
        "pd": pd,
        "rankdata": rankdata,
        "xr": xr,
    }


def _git_sha() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _version(name: str) -> str:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return "not installed"


def acquire_pair_input(path: Path):
    """Acquire the bounded observed PRISM pair cube through the public loader."""

    if path.exists():
        print(f"using existing observed pair input: {path}")
        return
    import cubedynamics as cd

    path.parent.mkdir(parents=True, exist_ok=True)
    source = cd.load_prism_cube(
        variables=["tmin", "tmax"],
        start="2023-11-01",
        end="2024-01-30",
        bbox=[-105.75, 39.50, -104.75, 40.50],
        freq="D",
        chunks={"time": 31, "y": 64, "x": 64},
        prefer_streaming=True,
        show_progress=False,
        allow_synthetic=False,
    )
    if bool(source.attrs.get("is_synthetic", True)):
        raise RuntimeError("Refusing synthetic PRISM input")
    observed = source.compute()
    observed.attrs.update(dict(source.attrs))
    observed.to_netcdf(path, engine="scipy")
    print(f"acquired observed pair input: {path}")


def _nearest_index(values, target, np) -> int:
    target64 = np.datetime64(target)
    return int(np.argmin(np.abs(values.astype("datetime64[ns]") - target64)))


def _coord_index(values, target, np) -> int:
    return int(np.argmin(np.abs(np.asarray(values, dtype=float) - float(target))))


def _manual_spearman(left, right, mask, np, rankdata) -> float:
    left_rank = rankdata(np.asarray(left)[mask], method="average")
    right_rank = rankdata(np.asarray(right)[mask], method="average")
    return float(np.corrcoef(left_rank, right_rank)[0, 1])


def _write_intermediates(
    *, output_dir, pair, snapshot, distance_frame, regional_frame, provenance, xr
):
    intermediate = output_dir / "intermediate"
    intermediate.mkdir(parents=True, exist_ok=True)
    pair["frame"].to_csv(intermediate / "pair_audit.csv", index=False)
    distance_frame.to_csv(intermediate / "distance_snapshot.csv", index=False)
    regional_frame.to_csv(intermediate / "regional_summary.csv", index=False)
    snapshot.to_netcdf(intermediate / "synchrony_snapshot.nc", engine="scipy")
    (output_dir / "provenance.json").write_text(
        json.dumps(provenance, indent=2) + "\n", encoding="utf-8"
    )


def _load_and_verify(pair_input: Path, full_sync: Path, full_manifest: Path, modules):
    np = modules["np"]
    pd = modules["pd"]
    rankdata = modules["rankdata"]
    xr = modules["xr"]

    from cubedynamics import pipe, verbs as v
    from cubedynamics.synchrony.spatial import build_spatial_pairs
    from cubedynamics.utils.reference import center_pixel_indices

    if not pair_input.exists():
        raise FileNotFoundError(
            f"Missing observed 90-day PRISM input: {pair_input}. "
            "See the walkthrough README for the bounded acquisition command."
        )
    if not full_sync.exists() or not full_manifest.exists():
        raise FileNotFoundError(
            "Missing full-record PRISM synchrony artifact. Run "
            "examples/real_prism_median_split_synchrony.py first."
        )

    with xr.open_dataset(pair_input, engine="scipy") as source:
        pair_cube = source[["tmin", "tmax"]].load()
    if bool(pair_cube.attrs.get("is_synthetic", True)):
        raise RuntimeError("Pair-level input must be observed PRISM data")
    if pair_cube.sizes["time"] != 91:
        raise RuntimeError("Expected 91 inclusive daily labels in the 90-day span")

    center_y, center_x = center_pixel_indices(pair_cube["tmin"])
    focal_y = _coord_index(pair_cube["y"].values, FOCAL_COORD[0], np)
    focal_x = _coord_index(pair_cube["x"].values, FOCAL_COORD[1], np)
    end_time = pair_cube["time"].values[-1]

    synchrony = (
        pipe(pair_cube)
        | v.rolling_median_split_synchrony(
            lower_var="tmin",
            upper_var="tmax",
            window_days=WINDOW_DAYS,
            min_t=MIN_T,
            split_quantile=SPLIT_QUANTILE,
            output_stride=OUTPUT_STRIDE,
            output_times=[end_time],
        )
    ).unwrap().compute()

    cold_center = pair_cube["tmin"].isel(y=center_y, x=center_x).values
    cold_focal = pair_cube["tmin"].isel(y=focal_y, x=focal_x).values
    warm_center = pair_cube["tmax"].isel(y=center_y, x=center_x).values
    warm_focal = pair_cube["tmax"].isel(y=focal_y, x=focal_x).values

    cold_valid = np.isfinite(cold_center) & np.isfinite(cold_focal)
    warm_valid = np.isfinite(warm_center) & np.isfinite(warm_focal)
    cold_center_median = float(np.quantile(cold_center[cold_valid], SPLIT_QUANTILE))
    cold_focal_median = float(np.quantile(cold_focal[cold_valid], SPLIT_QUANTILE))
    warm_center_median = float(np.quantile(warm_center[warm_valid], 1 - SPLIT_QUANTILE))
    warm_focal_median = float(np.quantile(warm_focal[warm_valid], 1 - SPLIT_QUANTILE))
    cold_mask = (
        cold_valid
        & (cold_center <= cold_center_median)
        & (cold_focal <= cold_focal_median)
    )
    warm_mask = (
        warm_valid
        & (warm_center > warm_center_median)
        & (warm_focal > warm_focal_median)
    )
    manual_cold = _manual_spearman(cold_center, cold_focal, cold_mask, np, rankdata)
    manual_warm = _manual_spearman(warm_center, warm_focal, warm_mask, np, rankdata)
    package_cold = float(synchrony["bottom_synchrony"].isel(time_window_end=0, y=focal_y, x=focal_x))
    package_warm = float(synchrony["top_synchrony"].isel(time_window_end=0, y=focal_y, x=focal_x))
    package_difference = float(synchrony["bottom_minus_top"].isel(time_window_end=0, y=focal_y, x=focal_x))
    np.testing.assert_allclose(manual_cold, package_cold, rtol=0, atol=1e-7)
    np.testing.assert_allclose(manual_warm, package_warm, rtol=0, atol=1e-7)
    np.testing.assert_allclose(package_difference, package_cold - package_warm, rtol=0, atol=1e-7)

    pair_set = build_spatial_pairs(pair_cube["tmin"], mode="reference", reference="center")
    focal_flat = focal_y * pair_cube.sizes["x"] + focal_x
    focal_distance = float(pair_set.distances[focal_flat])
    frame = pd.DataFrame(
        {
            "time": pd.DatetimeIndex(pair_cube["time"].values),
            "center_tmin_degC": cold_center,
            "focal_tmin_degC": cold_focal,
            "center_tmax_degC": warm_center,
            "focal_tmax_degC": warm_focal,
            "jointly_cold": cold_mask,
            "jointly_warm": warm_mask,
        }
    )
    pair = {
        "cube": pair_cube,
        "synchrony": synchrony,
        "frame": frame,
        "center_index": (center_y, center_x),
        "focal_index": (focal_y, focal_x),
        "center_coord": (float(pair_cube["y"][center_y]), float(pair_cube["x"][center_x])),
        "focal_coord": (float(pair_cube["y"][focal_y]), float(pair_cube["x"][focal_x])),
        "distance_km": focal_distance,
        "cold_center_median": cold_center_median,
        "cold_focal_median": cold_focal_median,
        "warm_center_median": warm_center_median,
        "warm_focal_median": warm_focal_median,
        "cold_count": int(cold_mask.sum()),
        "warm_count": int(warm_mask.sum()),
        "cold_rho": package_cold,
        "warm_rho": package_warm,
        "difference": package_difference,
    }

    with xr.open_dataset(full_sync, engine="scipy") as source:
        full = source.load()
    manifest = json.loads(full_manifest.read_text(encoding="utf-8"))
    if bool(manifest.get("is_synthetic", True)):
        raise RuntimeError("Full-record synchrony input must be observed PRISM data")
    snapshot_index = _nearest_index(full["time_window_end"].values, SNAPSHOT_TARGET, np)
    snapshot = full.isel(time_window_end=snapshot_index).copy()
    snapshot_time = pd.Timestamp(full["time_window_end"].values[snapshot_index])

    full_center_y, full_center_x = center_pixel_indices(full["bottom_synchrony"])
    snapshot_pairs = build_spatial_pairs(
        full["bottom_synchrony"], mode="reference", reference="center"
    )
    flat_y, flat_x = np.meshgrid(
        np.arange(full.sizes["y"]), np.arange(full.sizes["x"]), indexing="ij"
    )
    distance_frame = pd.DataFrame(
        {
            "y_index": flat_y.ravel(),
            "x_index": flat_x.ravel(),
            "latitude": np.repeat(full["y"].values, full.sizes["x"]),
            "longitude": np.tile(full["x"].values, full.sizes["y"]),
            "distance_km": np.asarray(snapshot_pairs.distances),
            "cold_synchrony": snapshot["bottom_synchrony"].values.ravel(),
            "warm_synchrony": snapshot["top_synchrony"].values.ravel(),
            "cold_minus_warm": snapshot["bottom_minus_top"].values.ravel(),
        }
    )
    regional = full.median(dim=("y", "x"), skipna=True)
    regional_frame = regional.to_dataframe().reset_index()
    full_context = {
        "full": full,
        "snapshot": snapshot,
        "snapshot_time": snapshot_time,
        "manifest": manifest,
        "center_index": (full_center_y, full_center_x),
        "center_coord": (float(full["y"][full_center_y]), float(full["x"][full_center_x])),
        "distance_frame": distance_frame,
        "regional_frame": regional_frame,
    }
    return pair, full_context


def _setup_style(plt):
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 12,
            "axes.titlesize": 16,
            "axes.labelsize": 12,
            "axes.edgecolor": GRID,
            "axes.linewidth": 0.8,
            "xtick.color": MUTED,
            "ytick.color": MUTED,
            "text.color": INK,
            "axes.labelcolor": INK,
            "figure.facecolor": PAPER,
            "axes.facecolor": WHITE,
            "savefig.facecolor": PAPER,
        }
    )


def _page(plt, number: int, title: str, kicker: str):
    fig = plt.figure(figsize=(PAGE_WIDTH, PAGE_HEIGHT), facecolor=PAPER)
    fig.text(0.055, 0.925, kicker.upper(), color=MUTED, fontsize=9, weight="bold")
    fig.text(0.055, 0.862, title, color=INK, fontsize=25, weight="bold")
    fig.add_artist(plt.Line2D([0.055, 0.945], [0.835, 0.835], color=GRID, lw=1.0))
    fig.text(0.055, 0.028, "CubeDynamics  |  observed PRISM  |  center-reference climate-tail synchrony", color=MUTED, fontsize=8)
    fig.text(0.945, 0.028, f"{number:02d} / 10", color=MUTED, fontsize=8, ha="right")
    return fig


def _save_page(fig, path, plt):
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=DPI, bbox_inches=None, facecolor=PAPER)
    plt.close(fig)


def _map_extent(da):
    x = da["x"].values
    y = da["y"].values
    dx = abs(float(x[1] - x[0])) if len(x) > 1 else 1.0
    dy = abs(float(y[1] - y[0])) if len(y) > 1 else 1.0
    return [float(x.min() - dx / 2), float(x.max() + dx / 2), float(y.min() - dy / 2), float(y.max() + dy / 2)]


def _plot_center_focal(ax, center_coord, focal_coord, *, center_label=True, focal_label=True):
    cy, cx = center_coord
    fy, fx = focal_coord
    ax.scatter(cx, cy, marker="*", s=230, color=CENTER, edgecolor=INK, linewidth=1.3, zorder=8)
    ax.scatter(fx, fy, marker="D", s=85, color=FOCAL, edgecolor=WHITE, linewidth=1.2, zorder=8)
    if center_label:
        ax.annotate("CENTER", (cx, cy), xytext=(8, 8), textcoords="offset points", fontsize=9, weight="bold", color=INK)
    if focal_label:
        ax.annotate("FOCAL", (fx, fy), xytext=(8, -14), textcoords="offset points", fontsize=9, weight="bold", color=FOCAL)


def _clean_axis(ax):
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(color=GRID, linewidth=0.7, alpha=0.65)


def _page_01(pair, modules):
    plt = modules["plt"]
    fig = _page(plt, 1, "What are we measuring?", "The scientific question")
    ax = fig.add_axes([0.055, 0.115, 0.46, 0.67])
    cube = pair["cube"]
    date_index = _nearest_index(cube.time.values, "2024-01-16", modules["np"])
    face = cube.tmin.isel(time=date_index)
    image = ax.imshow(face.values, extent=_map_extent(face), origin="upper", cmap="Blues_r", aspect="auto", interpolation="nearest")
    _plot_center_focal(ax, pair["center_coord"], pair["focal_coord"])
    ax.set(xlabel="longitude", ylabel="latitude", title="PRISM daily minimum temperature | 16 Jan 2024")
    cb = fig.colorbar(image, ax=ax, fraction=0.046, pad=0.03)
    cb.set_label("tmin (degC)")

    fig.text(0.57, 0.70, "How synchronized is climate", fontsize=23, weight="bold", color=INK)
    fig.text(0.57, 0.64, "at every location with one focal center?", fontsize=18, color=INK)
    fig.text(0.57, 0.53, "And does that synchrony differ", fontsize=18, color=INK)
    fig.text(0.57, 0.47, "between cold and warm conditions?", fontsize=18, color=INK)
    fig.text(0.62, 0.29, "pixel i", fontsize=17, color=FOCAL, weight="bold", ha="center")
    fig.text(0.78, 0.29, "CENTER", fontsize=17, color=INK, weight="bold", ha="center")
    fig.patches.append(modules["FancyBboxPatch"]((0.57, 0.21), 0.13, 0.13, boxstyle="round,pad=0.02", fc="#F8E8EF", ec=FOCAL, transform=fig.transFigure))
    fig.patches.append(modules["FancyBboxPatch"]((0.72, 0.21), 0.13, 0.13, boxstyle="round,pad=0.02", fc="#FFF3CF", ec=CENTER, transform=fig.transFigure))
    ax_arrow = fig.add_axes([0, 0, 1, 1], frameon=False)
    ax_arrow.set_axis_off()
    ax_arrow.annotate("", xy=(0.72, 0.275), xytext=(0.70, 0.275), xycoords="axes fraction", arrowprops=dict(arrowstyle="->", lw=2.2, color=INK))
    fig.text(0.57, 0.12, "Every pixel is compared with the SAME center reference.", fontsize=12.5, weight="bold", color=INK)
    return fig


def _page_02(pair, modules):
    plt, np = modules["plt"], modules["np"]
    from cubedynamics.synchrony.spatial import build_spatial_pairs

    fig = _page(plt, 2, "The reference geometry", "One center, many directed comparisons")
    ax = fig.add_axes([0.055, 0.115, 0.58, 0.67])
    mean_face = pair["cube"].tmin.mean("time")
    ax.imshow(mean_face.values, extent=_map_extent(mean_face), origin="upper", cmap="Greys", alpha=0.45, aspect="auto", interpolation="nearest")
    pair_set = build_spatial_pairs(pair["cube"].tmin, mode="reference", reference="center")
    cy, cx = pair["center_coord"]
    examples = [
        (12, 14, "nearby", COLD),
        (*pair["focal_index"], "intermediate / focal", FOCAL),
        (0, 24, "distant", DIFF),
    ]
    for yi, xi, label, color in examples:
        y = float(pair["cube"].y[yi]); x = float(pair["cube"].x[xi])
        flat = yi * pair["cube"].sizes["x"] + xi
        distance = pair_set.distances[flat]
        ax.plot([x, cx], [y, cy], color=color, lw=2.0, alpha=0.85)
        ax.scatter(x, y, s=70, marker="D", color=color, edgecolor=WHITE, zorder=6)
        ax.annotate(f"{label}\n{distance:.1f} km", (x, y), xytext=(7, 7), textcoords="offset points", fontsize=9, color=color, weight="bold")
    ax.scatter(cx, cy, marker="*", s=260, color=CENTER, edgecolor=INK, linewidth=1.2, zorder=8)
    ax.annotate("CENTER / reference", (cx, cy), xytext=(8, -18), textcoords="offset points", fontsize=10, weight="bold")
    ax.set(xlabel="longitude", ylabel="latitude", title="Actual 25 x 25 PRISM grid")

    fig.text(0.68, 0.69, "REFERENCE mode", fontsize=17, weight="bold", color=INK)
    fig.text(0.70, 0.59, "A  ->  C", fontsize=18, color=INK, family="monospace")
    fig.text(0.70, 0.52, "B  ->  C", fontsize=18, color=INK, family="monospace")
    fig.text(0.70, 0.45, "D  ->  C", fontsize=18, color=INK, family="monospace")
    fig.text(0.68, 0.34, "not neighbor-to-neighbor", fontsize=13, color=MUTED)
    fig.text(0.68, 0.25, "Distance is calculated by CubeDynamics\nfrom each grid coordinate to the center\n(great-circle kilometers for lon/lat).", fontsize=11.5, color=INK, linespacing=1.5)
    return fig


def _page_03(pair, modules):
    plt, mdates = modules["plt"], modules["mdates"]
    fig = _page(plt, 3, "One pixel versus the center", "Separate local distributions")
    frame = pair["frame"]
    ax = fig.add_axes([0.075, 0.25, 0.85, 0.49])
    ax.plot(frame.time, frame.center_tmin_degC, color=INK, lw=2.2, label="center tmin")
    ax.plot(frame.time, frame.focal_tmin_degC, color=FOCAL, lw=2.0, label="focal tmin")
    ax.axhline(pair["cold_center_median"], color=INK, lw=1.2, ls="--")
    ax.axhline(pair["cold_focal_median"], color=FOCAL, lw=1.2, ls="--")
    ax.text(frame.time.iloc[-1], pair["cold_center_median"] + 0.4, f"center median {pair['cold_center_median']:.1f} degC", ha="right", color=INK, fontsize=10)
    ax.text(frame.time.iloc[-1], pair["cold_focal_median"] - 1.0, f"focal median {pair['cold_focal_median']:.1f} degC", ha="right", color=FOCAL, fontsize=10)
    ax.set(ylabel="daily minimum temperature (degC)", xlabel="inclusive trailing window end: 30 Jan 2024")
    ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b"))
    _clean_axis(ax)
    ax.legend(frameon=False, ncol=2, loc="upper left")
    fig.text(0.075, 0.78, "90-day coordinate span  |  91 inclusive daily labels  |  1 Nov 2023 - 30 Jan 2024", fontsize=11, color=MUTED)
    fig.text(0.21, 0.12, "T_i(t) <= median(T_i)", fontsize=15, color=FOCAL, weight="bold", ha="center")
    fig.text(0.43, 0.12, "AND", fontsize=15, color=INK, weight="bold", ha="center")
    fig.text(0.67, 0.12, "T_c(t) <= median(T_c)", fontsize=15, color=INK, weight="bold", ha="center")
    fig.text(0.50, 0.083, "Separate local thresholds - not one shared temperature cutoff", fontsize=10.5, color=MUTED, ha="center")
    return fig


def _tail_page(pair, modules, *, warm: bool):
    plt, mdates = modules["plt"], modules["mdates"]
    number = 5 if warm else 4
    title = "Selecting jointly warm observations" if warm else "Selecting jointly cold observations"
    kicker = "tmax above each median" if warm else "tmin at or below each median"
    color = WARM if warm else COLD
    fig = _page(plt, number, title, kicker)
    frame = pair["frame"]
    center_col = "center_tmax_degC" if warm else "center_tmin_degC"
    focal_col = "focal_tmax_degC" if warm else "focal_tmin_degC"
    mask_col = "jointly_warm" if warm else "jointly_cold"
    mask = frame[mask_col].to_numpy()
    center = frame[center_col].to_numpy(); focal = frame[focal_col].to_numpy()
    center_median = pair["warm_center_median"] if warm else pair["cold_center_median"]
    focal_median = pair["warm_focal_median"] if warm else pair["cold_focal_median"]
    rho = pair["warm_rho"] if warm else pair["cold_rho"]
    count = pair["warm_count"] if warm else pair["cold_count"]

    ax1 = fig.add_axes([0.065, 0.18, 0.53, 0.56])
    ax1.plot(frame.time, center, color=INK, alpha=0.35, lw=1.3)
    ax1.plot(frame.time, focal, color=FOCAL, alpha=0.35, lw=1.3)
    ax1.scatter(frame.time[mask], center[mask], color=color, s=27, marker="o", label="center selected", zorder=5)
    ax1.scatter(frame.time[mask], focal[mask], color=color, s=30, marker="D", edgecolor=WHITE, linewidth=0.4, label="focal selected", zorder=5)
    ax1.axhline(center_median, color=INK, ls="--", lw=1.0)
    ax1.axhline(focal_median, color=FOCAL, ls="--", lw=1.0)
    ax1.set(ylabel=("daily maximum temperature (degC)" if warm else "daily minimum temperature (degC)"), xlabel="date")
    ax1.xaxis.set_major_locator(mdates.WeekdayLocator(interval=3))
    ax1.xaxis.set_major_formatter(mdates.DateFormatter("%d %b"))
    _clean_axis(ax1)
    ax1.legend(frameon=False, fontsize=9, ncol=2, loc="upper left")

    ax2 = fig.add_axes([0.66, 0.24, 0.28, 0.44])
    ax2.scatter(center, focal, color="#C9D0D3", s=23, alpha=0.65, label="not used")
    ax2.scatter(center[mask], focal[mask], color=color, s=48, edgecolor=WHITE, linewidth=0.5, label="joint tail", zorder=5)
    ax2.axvline(center_median, color=INK, ls="--", lw=0.9)
    ax2.axhline(focal_median, color=FOCAL, ls="--", lw=0.9)
    ax2.set(xlabel=("center tmax (degC)" if warm else "center tmin (degC)"), ylabel=("focal tmax (degC)" if warm else "focal tmin (degC)"))
    _clean_axis(ax2)
    inclusion = "> own medians" if warm else "<= own medians"
    fig.text(0.80, 0.72, f"BOTH {inclusion}", ha="center", color=color, fontsize=12, weight="bold")
    fig.text(0.80, 0.15, f"n window = 91   |   n joint = {count}\nSpearman rho = {rho:.3f}", ha="center", va="center", fontsize=13, color=INK, weight="bold", linespacing=1.5)
    return fig


def _page_06(pair, modules):
    plt = modules["plt"]
    fig = _page(plt, 6, "One pixel produces two synchrony values", "Pair result -> one map cell")
    fig.text(0.09, 0.66, "S_cold", fontsize=19, color=COLD, weight="bold")
    fig.text(0.22, 0.66, f"= {pair['cold_rho']:.3f}", fontsize=27, color=INK, weight="bold")
    fig.text(0.09, 0.54, "S_warm", fontsize=19, color=WARM, weight="bold")
    fig.text(0.22, 0.54, f"= {pair['warm_rho']:.3f}", fontsize=27, color=INK, weight="bold")
    fig.text(0.09, 0.39, "Delta S", fontsize=20, color=DIFF, weight="bold")
    fig.text(0.22, 0.39, f"= {pair['cold_rho']:.3f} - {pair['warm_rho']:.3f} = {pair['difference']:.3f}", fontsize=24, color=INK, weight="bold")
    interpretation = "stronger warm synchrony" if pair["difference"] < 0 else "stronger cold synchrony"
    fig.text(0.09, 0.27, f"This focal pixel: {interpretation}", fontsize=16, color=WARM if pair["difference"] < 0 else COLD, weight="bold")
    fig.text(0.09, 0.16, "Delta S > 0  cold stronger\nDelta S < 0  warm stronger\nDelta S near 0  similar tail synchrony", fontsize=11, color=MUTED, linespacing=1.5)

    ax = fig.add_axes([0.58, 0.16, 0.34, 0.58])
    face = pair["cube"].tmin.mean("time")
    ax.imshow(face.values, extent=_map_extent(face), origin="upper", cmap="Greys", alpha=0.40, aspect="auto", interpolation="nearest")
    _plot_center_focal(ax, pair["center_coord"], pair["focal_coord"])
    ax.plot([pair["focal_coord"][1], pair["center_coord"][1]], [pair["focal_coord"][0], pair["center_coord"][0]], color=FOCAL, lw=2)
    ax.set(xlabel="longitude", ylabel="latitude", title=f"Focal cell is {pair['distance_km']:.1f} km from center")
    return fig


def _page_07(pair, full_context, modules):
    plt = modules["plt"]
    fig = _page(plt, 7, "Repeat the calculation for every pixel", "One 90-day rolling window -> three maps")
    fig.text(0.5, 0.79, "EVERY PIXEL  ->  SAME CENTER", ha="center", fontsize=14, color=INK, weight="bold")
    snapshot = full_context["snapshot"]
    center_coord = full_context["center_coord"]
    focal_coord = pair["focal_coord"]
    panels = [
        ("bottom_synchrony", "A  Cold synchrony, S_cold", "Blues", -1, 1),
        ("top_synchrony", "B  Warm synchrony, S_warm", "Oranges", -1, 1),
        ("bottom_minus_top", "C  Delta S = cold - warm", "RdBu_r", -1, 1),
    ]
    last = None
    for i, (name, title, cmap, vmin, vmax) in enumerate(panels):
        ax = fig.add_axes([0.045 + i * 0.32, 0.19, 0.27, 0.49])
        da = snapshot[name]
        last = ax.imshow(da.values, extent=_map_extent(da), origin="upper", cmap=cmap, vmin=vmin, vmax=vmax, aspect="auto", interpolation="nearest")
        _plot_center_focal(ax, center_coord, focal_coord, center_label=False, focal_label=False)
        ax.set_title(title, fontsize=13, weight="bold")
        ax.set_xlabel("longitude")
        if i == 0:
            ax.set_ylabel("latitude")
        else:
            ax.set_yticklabels([])
        cb = fig.colorbar(last, ax=ax, orientation="horizontal", fraction=0.06, pad=0.14)
        cb.set_label("Spearman rho" if i < 2 else "Delta S", fontsize=9)
    fig.text(0.5, 0.105, f"Observed PRISM | window end {full_context['snapshot_time'].date()} | shared synchrony limits [-1, 1] | difference centered at zero | white = undefined (< {MIN_T} joint observations)", ha="center", fontsize=9.5, color=MUTED)
    return fig


def _binned_median(frame, x_name, y_name, pd, np, bins=9):
    clean = frame[[x_name, y_name]].dropna().copy()
    clean["bin"] = pd.cut(clean[x_name], bins=np.linspace(clean[x_name].min(), clean[x_name].max(), bins + 1), include_lowest=True)
    grouped = clean.groupby("bin", observed=True).agg({x_name: "median", y_name: "median"}).dropna()
    return grouped[x_name].to_numpy(), grouped[y_name].to_numpy()


def _page_08(pair, full_context, modules):
    plt, pd, np = modules["plt"], modules["pd"], modules["np"]
    fig = _page(plt, 8, "Synchrony versus distance from the center", "Exploratory spatial decay diagnostic")
    frame = full_context["distance_frame"]
    focal = frame.iloc[((frame.latitude - pair["focal_coord"][0]).abs() + (frame.longitude - pair["focal_coord"][1]).abs()).argmin()]
    panels = [("cold_synchrony", COLD, "Cold synchrony"), ("warm_synchrony", WARM, "Warm synchrony"), ("cold_minus_warm", DIFF, "Delta S")]
    for i, (name, color, title) in enumerate(panels):
        ax = fig.add_axes([0.055 + i * 0.315, 0.19, 0.27, 0.53])
        ax.scatter(frame.distance_km, frame[name], s=16, color=color, alpha=0.30, edgecolors="none")
        bx, by = _binned_median(frame, "distance_km", name, pd, np)
        ax.plot(bx, by, color=INK, lw=2.3, marker="o", ms=4, label="binned median")
        ax.scatter(focal.distance_km, focal[name], s=95, marker="D", color=FOCAL, edgecolor=WHITE, linewidth=1.0, zorder=8)
        if name == "cold_minus_warm": ax.axhline(0, color=INK, lw=0.9, alpha=0.65)
        ax.set(xlabel="distance from center (km)", ylabel=("Spearman rho" if i < 2 else "Delta S"), title=title)
        ax.set_ylim((-1.05, 1.05) if i < 2 else (-1.05, 1.05))
        _clean_axis(ax)
        if i == 0: ax.legend(frameon=False, fontsize=9)
    fig.text(0.055, 0.105, "Diamond = focal example. Line = descriptive binned median, not a fitted mechanism or formal synchrony length.", fontsize=10.5, color=MUTED)
    fig.text(0.945, 0.105, f"Window end: {full_context['snapshot_time'].date()}", fontsize=10.5, color=MUTED, ha="right")
    return fig


def _page_09(full_context, modules):
    plt, mdates = modules["plt"], modules["mdates"]
    fig = _page(plt, 9, "The rolling window moves through time", "A synchrony cube: x × y × rolling time")
    regional = full_context["regional_frame"]
    ax = fig.add_axes([0.07, 0.22, 0.86, 0.48])
    ax.plot(regional.time_window_end, regional.bottom_synchrony, color=COLD, lw=1.55, label="median S_cold")
    ax.plot(regional.time_window_end, regional.top_synchrony, color=WARM, lw=1.55, label="median S_warm")
    ax.plot(regional.time_window_end, regional.bottom_minus_top, color=DIFF, lw=1.2, alpha=0.85, label="median Delta S")
    ax.axhline(0, color=INK, lw=0.8, alpha=0.5)
    ax.set(xlabel="rolling-window end", ylabel="spatial median synchrony")
    ax.xaxis.set_major_locator(mdates.YearLocator(5))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    _clean_axis(ax)
    ax.legend(frameon=False, ncol=3, loc="lower left")
    fig.text(0.07, 0.75, "1981-2025 observed PRISM  |  90-day coordinate span  |  output_stride=30 (~monthly)  |  547 maps", fontsize=11, color=MUTED)
    # Compact moving-window schematic.
    fig.text(0.68, 0.78, "daily record", fontsize=9, color=MUTED)
    fig.add_artist(plt.Line2D([0.76, 0.92], [0.785, 0.785], transform=fig.transFigure, color=GRID, lw=5))
    fig.add_artist(plt.Line2D([0.82, 0.88], [0.785, 0.785], transform=fig.transFigure, color=COLD, lw=8))
    fig.text(0.85, 0.805, "90-day span", fontsize=9, ha="center", color=COLD, weight="bold")
    fig.text(0.93, 0.78, "+30 d ->", fontsize=9, color=INK)
    fig.text(0.50, 0.105, "Each output is a spatial map; stacking map after map produces a relationship cube.", ha="center", fontsize=11.2, color=INK, weight="bold")
    return fig


def _flow_box(fig, modules, x, y, w, h, text, *, fc=WHITE, ec=GRID, color=INK, fontsize=11):
    patch = modules["FancyBboxPatch"]((x, y), w, h, boxstyle="round,pad=0.012,rounding_size=0.015", fc=fc, ec=ec, lw=1.4, transform=fig.transFigure)
    fig.patches.append(patch)
    fig.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fontsize, color=color, weight="bold")


def _arrow(fig, modules, start, end):
    ax = fig.add_axes([0, 0, 1, 1], frameon=False)
    ax.set_axis_off()
    ax.annotate("", xy=end, xytext=start, xycoords="axes fraction", arrowprops=dict(arrowstyle="->", lw=1.6, color=MUTED))


def _page_10(modules):
    plt = modules["plt"]
    fig = _page(plt, 10, "The complete calculation", "From observed temperatures to an interpretable synchrony cube")
    _flow_box(fig, modules, 0.06, 0.64, 0.16, 0.09, "PRISM tmin / tmax\ncube", fc="#EAF1F7", ec=COLD)
    _flow_box(fig, modules, 0.29, 0.64, 0.16, 0.09, "choose center\npixel", fc="#FFF3CF", ec=CENTER)
    _flow_box(fig, modules, 0.52, 0.64, 0.16, 0.09, "rolling 90-day\ncoordinate span")
    _flow_box(fig, modules, 0.75, 0.64, 0.18, 0.09, "each pixel +\nsame center")
    for a, b in [((0.22, 0.685), (0.29, 0.685)), ((0.45, 0.685), (0.52, 0.685)), ((0.68, 0.685), (0.75, 0.685))]: _arrow(fig, modules, a, b)

    _flow_box(fig, modules, 0.37, 0.46, 0.26, 0.09, "split each series by\nits own rolling median", fc="#F1EEF6", ec=DIFF)
    _arrow(fig, modules, (0.84, 0.64), (0.63, 0.55))
    _flow_box(fig, modules, 0.16, 0.28, 0.25, 0.10, "jointly cold\ntmin <= own medians", fc="#E8F2FA", ec=COLD, color=COLD)
    _flow_box(fig, modules, 0.59, 0.28, 0.25, 0.10, "jointly warm\ntmax > own medians", fc="#FCECE8", ec=WARM, color=WARM)
    _arrow(fig, modules, (0.45, 0.46), (0.33, 0.38)); _arrow(fig, modules, (0.55, 0.46), (0.67, 0.38))
    _flow_box(fig, modules, 0.16, 0.15, 0.25, 0.07, "Spearman -> S_cold", fc=WHITE, ec=COLD, color=COLD)
    _flow_box(fig, modules, 0.59, 0.15, 0.25, 0.07, "Spearman -> S_warm", fc=WHITE, ec=WARM, color=WARM)
    _arrow(fig, modules, (0.285, 0.28), (0.285, 0.22)); _arrow(fig, modules, (0.715, 0.28), (0.715, 0.22))
    _flow_box(fig, modules, 0.39, 0.06, 0.22, 0.065, "Delta S = S_cold - S_warm\nMaps -> distance + time", fc="#F1EEF6", ec=DIFF, color=DIFF, fontsize=10.5)
    _arrow(fig, modules, (0.285, 0.15), (0.44, 0.125)); _arrow(fig, modules, (0.715, 0.15), (0.56, 0.125))
    fig.text(0.50, 0.79, "Synchrony asks whether fluctuations at each location move with a common focal location,\nconditional on both locations occupying the same cold or warm part of their own local distributions.", ha="center", fontsize=11.2, color=INK, linespacing=1.35)
    return fig


def generate_pages(output_dir: Path, pair_input: Path, full_sync: Path, full_manifest: Path):
    modules = _heavy_imports()
    plt, xr = modules["plt"], modules["xr"]
    _setup_style(plt)
    pair, full_context = _load_and_verify(pair_input, full_sync, full_manifest, modules)
    pages_dir = output_dir / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)

    builders = [
        lambda: _page_01(pair, modules),
        lambda: _page_02(pair, modules),
        lambda: _page_03(pair, modules),
        lambda: _tail_page(pair, modules, warm=False),
        lambda: _tail_page(pair, modules, warm=True),
        lambda: _page_06(pair, modules),
        lambda: _page_07(pair, full_context, modules),
        lambda: _page_08(pair, full_context, modules),
        lambda: _page_09(full_context, modules),
        lambda: _page_10(modules),
    ]
    page_paths = []
    for index, builder in enumerate(builders, start=1):
        path = pages_dir / f"page_{index:02d}.png"
        _save_page(builder(), path, plt)
        page_paths.append(path)

    provenance = {
        "schema_version": 1,
        "generated_on": date.today().isoformat(),
        "git_commit_sha": _git_sha(),
        "data_source": "PRISM Climate Group observed daily tmin and tmax",
        "is_synthetic": False,
        "pair_input": str(pair_input.resolve()),
        "pair_bbox": [-105.75, 39.5, -104.75, 40.5],
        "pair_date_range": [str(pair["frame"].time.iloc[0].date()), str(pair["frame"].time.iloc[-1].date())],
        "full_record_synchrony": str(full_sync.resolve()),
        "full_record_date_range": [full_context["manifest"]["start"], full_context["manifest"]["end"]],
        "variables": ["tmin", "tmax"],
        "window_days": WINDOW_DAYS,
        "inclusive_daily_labels_in_pair_window": int(pair["cube"].sizes["time"]),
        "output_stride": OUTPUT_STRIDE,
        "minimum_observations_per_tail": MIN_T,
        "split_quantile": SPLIT_QUANTILE,
        "center_pixel_index": list(pair["center_index"]),
        "center_pixel_coordinates_lat_lon": list(pair["center_coord"]),
        "focal_pixel_index": list(pair["focal_index"]),
        "focal_pixel_coordinates_lat_lon": list(pair["focal_coord"]),
        "focal_distance_km": pair["distance_km"],
        "demonstration": {
            "jointly_cold_count": pair["cold_count"],
            "jointly_warm_count": pair["warm_count"],
            "cold_spearman": pair["cold_rho"],
            "warm_spearman": pair["warm_rho"],
            "cold_minus_warm": pair["difference"],
            "manual_vs_package_tolerance": 1e-7,
        },
        "software": {
            "python": platform.python_version(),
            "cubedynamics": _version("cubedynamics"),
            "numpy": _version("numpy"),
            "xarray": _version("xarray"),
            "scipy": _version("scipy"),
            "matplotlib": _version("matplotlib"),
        },
        "implementation_note": (
            "rolling_tail_dep_vs_center slices inclusively from end - window_days "
            "through end; uninterrupted daily data therefore contain 91 labels for window_days=90"
        ),
    }
    _write_intermediates(
        output_dir=output_dir,
        pair=pair,
        snapshot=full_context["snapshot"],
        distance_frame=full_context["distance_frame"],
        regional_frame=full_context["regional_frame"],
        provenance=provenance,
        xr=xr,
    )
    return page_paths, provenance


def compose_pdf(page_paths: list[Path], pdf_path: Path):
    try:
        from reportlab.lib.utils import ImageReader
        from reportlab.pdfgen import canvas
    except ImportError as exc:
        raise RuntimeError(
            "PDF composition requires reportlab. Install it or run --compose-only "
            "with the bundled Codex PDF runtime."
        ) from exc

    width = PAGE_WIDTH * 72
    height = PAGE_HEIGHT * 72
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    document = canvas.Canvas(str(pdf_path), pagesize=(width, height), pageCompression=1)
    document.setTitle("Center-pixel climate synchrony: a visual walkthrough")
    document.setAuthor("CubeDynamics")
    document.setSubject("Observed PRISM center-reference rolling climate-tail synchrony")
    for path in page_paths:
        document.drawImage(ImageReader(str(path)), 0, 0, width=width, height=height, preserveAspectRatio=False, mask="auto")
        document.showPage()
    document.save()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--pair-input", type=Path, default=DEFAULT_PAIR_INPUT)
    parser.add_argument("--full-synchrony", type=Path, default=DEFAULT_FULL_SYNC)
    parser.add_argument("--full-manifest", type=Path, default=DEFAULT_FULL_MANIFEST)
    parser.add_argument("--pages-only", action="store_true")
    parser.add_argument("--compose-only", action="store_true")
    parser.add_argument(
        "--acquire-pair-input",
        action="store_true",
        help="Acquire the bounded observed PRISM pair cube if it is absent",
    )
    args = parser.parse_args()
    if args.pages_only and args.compose_only:
        parser.error("--pages-only and --compose-only are mutually exclusive")

    output_dir = args.output_dir.resolve()
    if args.acquire_pair_input:
        acquire_pair_input(args.pair_input.resolve())
    pages = [output_dir / "pages" / f"page_{index:02d}.png" for index in range(1, 11)]
    provenance = None
    if not args.compose_only:
        pages, provenance = generate_pages(
            output_dir,
            args.pair_input.resolve(),
            args.full_synchrony.resolve(),
            args.full_manifest.resolve(),
        )
    missing = [str(path) for path in pages if not path.exists()]
    if missing:
        raise FileNotFoundError(f"Missing page images: {missing}")
    pdf_path = output_dir / "center_pixel_synchrony_walkthrough.pdf"
    if not args.pages_only:
        compose_pdf(pages, pdf_path)
        print(f"PDF: {pdf_path}")
    if provenance:
        demo = provenance["demonstration"]
        print(
            "pair audit: cold={cold_spearman:.9f}, warm={warm_spearman:.9f}, "
            "difference={cold_minus_warm:.9f}".format(**demo)
        )


if __name__ == "__main__":
    main()
