#!/usr/bin/env python3
"""Generate small, source-controlled MkDocs references from the runtime API.

Run with --check in CI. This module reads metadata and signatures only; it never
loads remote scientific data. Editorial examples live alongside this script.
"""
from __future__ import annotations

import argparse
import inspect
import json
import os
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from cubedynamics import data, verbs as v

DOCS = ROOT / "docs"
MARKER = "<!-- Generated by scripts/build_reference_docs.py; do not edit. -->\n\n"
FAMILIES = {"surface_reflectance": "Surface observations", "vegetation_index": "Vegetation"}
CLIMATE = {"temperature", "precipitation", "vpd", "wind", "humidity", "radiation"}
NOUN_DEFINITIONS = {
    "temperature": "Gridded air temperature, with an explicit daily statistic.",
    "precipitation": "Daily precipitation totals.",
    "vpd": "Mean daily vapor-pressure deficit.",
    "wind": "Wind velocity at 10 m height.",
    "humidity": "Daily maximum or minimum relative humidity.",
    "radiation": "Downward surface shortwave radiation.",
    "surface_reflectance": "Multispectral surface-reflectance bands.",
    "vegetation_index": "A derived vegetation index; currently NDVI.",
}
SOURCE_NOTES = {"prism": "datasets/prism.md", "gridmet": "datasets/gridmet.md", "sentinel2": "datasets/sentinel2_ndvi.md"}
NOUN_SECTIONS = ("Quick facts", "Usage", "Available sources", "Returned data", "Minimal reproducible example", "Quality and provenance", "See also")
SOURCE_SECTIONS = ("Provider", "Product", "What it provides", "Coverage", "Resolution", "Temporal coverage", "Access method", "Available CubeDynamics nouns", "Current QA/certification status", "Serving revision / provenance information", "Important limitations", "Examples using this source")
VERB_SECTIONS = ("Usage", "Arguments", "Accepts", "Returns", "Order / grammar behavior", "Minimal example", "Works with", "See also")


def public_verbs():
    # __all__ retains compatibility helpers. State/event factories are also
    # public imports even though the historical __all__ omits them.
    names = set(v.__all__) | {name for name, value in vars(v).items()
        if not name.startswith("_") and inspect.isfunction(value)
        and value.__module__.startswith("cubedynamics.verbs.")}
    return {name: getattr(v, name) for name in sorted(names)}


def family(noun):
    return "Climate & weather" if noun in CLIMATE else FAMILIES.get(noun, "Other")


def coverage_summary(noun, sources):
    entries = [data.describe(noun, source) for source in sources]
    return "; ".join(f"{e['source']}: {e['coverage']}, {e['spatial_resolution']}, {e['temporal_resolution']} ({e['temporal_coverage']})" for e in entries)


def link(page, target, label):
    return f"[{label}]({os.path.relpath(target, Path(page).parent)})"


def cell(value):
    if isinstance(value, dict):
        value = "; ".join(f"{k}: {cell(v)}" for k, v in value.items())
    elif isinstance(value, (tuple, list)):
        value = ", ".join(map(str, value))
    return str(value).replace("|", "&#124;").replace("\n", " ").replace("`", "")


def table(headers, rows):
    return "| " + " | ".join(headers) + " |\n| " + " | ".join(["---"] * len(headers)) + " |\n" + "\n".join("| " + " | ".join(map(cell, row)) + " |" for row in rows) + "\n"


def section(title, body):
    return f"\n## {title}\n\n{body.strip()}\n"


def summary(func):
    lines = (inspect.getdoc(func) or "").splitlines()
    while lines and (lines[0].strip() in {"Summary", ""} or set(lines[0]) == {"-"}):
        lines.pop(0)
    return next(iter(lines), "Public callable; consult the implementation notes below.")


def signature(func):
    sig = inspect.signature(func)
    return str(sig.replace(parameters=[p.replace(annotation=inspect.Parameter.empty) for p in sig.parameters.values()], return_annotation=inspect.Signature.empty))


def doc_sections(func):
    # Handle both NumPy headings and the short grammar-contract docstrings.
    result, current = {}, "Summary"
    for line in (inspect.getdoc(func) or "").splitlines():
        if line in {"Summary", "Parameters", "Returns", "Notes", "Examples", "See Also", "Grammar contract", "Raises"}:
            current = line
        elif line and set(line.strip()) != {"-"}:
            result.setdefault(current, []).append(line)
    return {key: "\n".join(value).strip() for key, value in result.items()}


def arguments(func):
    descriptions = {}
    active = []
    for line in doc_sections(func).get("Parameters", "").splitlines():
        if line and not line.startswith(" "):
            active = [s.strip().lstrip("*") for s in line.split(":")[0].split(",")]
            for name in active:
                descriptions[name] = []
        else:
            for name in active:
                descriptions[name].append(line.strip())
    rows = []
    for name, p in inspect.signature(func).parameters.items():
        description = " ".join(descriptions.get(name, []))
        if not description:
            description = "See implementation docstring below; no parameter-specific description supplied."
        default = "required" if p.default is inspect.Parameter.empty else repr(p.default)
        if p.kind in {p.VAR_POSITIONAL, p.VAR_KEYWORD}:
            default = "forwarded arguments"
        rows.append((name, description, default))
    return table(["Argument", "Meaning", "Default"], rows) if rows else "No arguments."


def vignette_links(page, name):
    found = []
    for path in sorted(DOCS.glob("**/*.ipynb")):
        nb = json.loads(path.read_text())
        if not nb.get("metadata", {}).get("cubedynamics", {}).get("supported_vignette"):
            continue
        code = "\n".join("".join(c["source"]) for c in nb["cells"] if c["cell_type"] == "code")
        if re.search(rf"\b(?:v|data)\.{re.escape(name)}\s*\(", code):
            title = next(("".join(c["source"]).splitlines()[0].lstrip("# ") for c in nb["cells"] if c["cell_type"] == "markdown"), path.stem)
            found.append(link(page, path.relative_to(DOCS), title))
    return found


def noun_example(noun, sources):
    source = "prism" if "prism" in sources else sources[0]
    location = 'lat=40.0, lon=-105.25' if source == "sentinel2" else 'bbox=[-105.55, 39.85, -105.05, 40.15]'
    optional = ', variables=["B04", "B08"]' if noun == "surface_reflectance" else ''
    plot = 'cube.isel(time=0, band=0).plot()' if noun == "surface_reflectance" else 'cube.isel(time=0).plot()'
    return f'''from cubedynamics import data
import matplotlib.pyplot as plt

cube = data.{noun}(
    source="{source}", {location},
    start="2024-06-01", end="2024-06-03"{optional},
)
{plot}
plt.show()'''


def generate():
    from docs_examples import EXAMPLES, FIXTURE_SETUP, NOTES
    pages = {}
    catalog = data.list_sources()
    index = "# Library\n\nFind environmental information by scientific noun. "
    index += "This index contains only implemented catalog entries. "
    index += "[Browse by source](sources/index.md), or look up an operation in [Documents](../reference/verbs/index.md).\n"
    index += "\nLooking for soil moisture, roads, streamflow, or other unlisted nouns? They are not implemented in this catalog. "
    index += "[Candidate integrations](../project/data_vocabulary_plan.md) are not available source flavors.\n"
    for group in sorted({family(noun) for noun in catalog}):
        index += section(group, table(["Noun", "Meaning", "Source flavors", "Coverage / resolution / time"], [
            (f"[{noun}](nouns/{noun}.md)", NOUN_DEFINITIONS.get(noun, summary(getattr(data, noun))), ", ".join(catalog[noun]), coverage_summary(noun, catalog[noun]))
            for noun in catalog if family(noun) == group]))
    index += section("Use and extend", "[Learn about source choice](../learn/provenance.md) · [Custom nouns](../extending/custom_nouns.md) · [Source QA](../data/phase1_qa.md)")
    pages["library/index.md"] = index

    for noun, sources in catalog.items():
        page = f"library/nouns/{noun}.md"
        entries = [data.describe(noun, s) for s in sources]
        text = f"# {noun}\n\n{NOUN_DEFINITIONS.get(noun, summary(getattr(data, noun)))}\n"
        text += section("Quick facts", table(["Fact", "Value"], [
            ("Semantic type", "Derived vegetation index" if noun == "vegetation_index" else "Gridded environmental observations"),
            ("Units by source", "; ".join(f"{e['source']}: {cell(e['units'])}" for e in entries)),
            ("Spatial coverage", "; ".join(sorted({e['coverage'] for e in entries}))),
            ("Temporal resolution", "; ".join(sorted({e['temporal_resolution'] for e in entries}))),
            ("Available source flavors", sources)]))
        text += section("Usage", f"```python\ndata.{noun}{signature(getattr(data, noun))}\n```\n\nImport with `from cubedynamics import data`. Keyword-only parameters and defaults above come from Python.")
        text += section("Available sources", table(["Source", "Coverage", "Resolution", "Time", "Selection constraint"], [
            (link(page, f"library/sources/{e['source']}.md", e['source']), e['coverage'], e['spatial_resolution'], e['temporal_coverage'] + "; " + e['temporal_resolution'], e['limitations']) for e in entries]))
        dims = "`time, band, y, x`" if noun == "surface_reflectance" else "`time, y, x`"
        output_name = "ndvi" if noun == "vegetation_index" else noun
        text += section("Returned data", f"An `xarray.DataArray` named `{output_name}`, normally with {dims} dimensions. `time` stores acquisition/observation times; `y` and `x` store grid coordinates in the declared CRS. Inspect the actual dimensions and CRS before combining sources.\n\nUnits are source-specific (above), not silently harmonized. Attributes include `scientific_noun`, `source_flavor`, `source_variables`, `source_provider`, `source_product`, `spatial_query`, `temporal_query`, `crs`, `retrieved_at`, `data_state`, and serving/schema provenance. See [provenance helpers](../../api/data.md).")
        text += section("Minimal reproducible example", "Network example: requires the provider and its optional dependencies. This is a real-data request, not an offline certification. For frozen inputs, use the [reviewed notebooks](../../vignettes/index.md).\n\n```python\n" + noun_example(noun, sources) + "\n```")
        text += section("Quality and provenance", table(["Source", "Lifecycle", "Revision", "Revision status", "Live health", "QA profile"], [(e['source'], e['lifecycle_state'], e['current_serving_revision'], e['revision_status'], e['live_health'], e['qa_profile']) for e in entries]) + "\nRevision validity is not a claim that the live endpoint is available today. [Certification evidence](../../data/phase1_qa.md) distinguishes reviewed fixtures from live checks. Each source's selection constraint above remains part of the interpretation.")
        related = vignette_links(page, noun)
        related += [link(page, "reference/verbs/mean.md", "mean"), link(page, "reference/verbs/anomaly.md", "anomaly"), link(page, "learn/nouns.md", "Learn: nouns"), link(page, "vignettes/index.md", "Real-data vignettes"), link(page, "library/index.md", "All nouns")]
        text += section("See also", "\n".join(f"- {item}" for item in related))
        pages[page] = text

    all_sources = sorted({s for sources in catalog.values() for s in sources})
    pages["library/sources/index.md"] = "# Sources\n\nImplemented catalog source flavors. Scientific nouns remain the primary [Library index](../index.md).\n\n" + table(["Source", "Provider", "Available nouns"], [
        (f"[{s}]({s}.md)", data.describe(next(n for n in catalog if s in catalog[n]), s)['provider'], ", ".join(n for n in catalog if s in catalog[n])) for s in all_sources]) + "\n[Daymet candidate](../../datasets/daymet.md) is not a promoted source. Other legacy adapters are described in [source configuration](../../api/data.md).\n"
    for source in all_sources:
        page = f"library/sources/{source}.md"
        entries = [data.describe(noun, source) for noun in catalog if source in catalog[noun]]
        text = f"# {source}\n"
        for title, key in [("Provider", "provider"), ("Product", "product"), ("What it provides", "source_variables"), ("Coverage", "coverage"), ("Resolution", "spatial_resolution"), ("Temporal coverage", "temporal_coverage"), ("Access method", "access_backend")]:
            text += section(title, table(["Noun", title], [(link(page, f"library/nouns/{e['noun']}.md", e['noun']), e[key]) for e in entries]))
        text += section("Available CubeDynamics nouns", ", ".join(link(page, f"library/nouns/{e['noun']}.md", e['noun']) for e in entries))
        text += section("Current QA/certification status", table(["Noun", "Lifecycle", "Revision status", "Live health", "QA profile"], [(e['noun'], e['lifecycle_state'], e['revision_status'], e['live_health'], e['qa_profile']) for e in entries]) + "\nThese are catalog declarations, not a new live certification. [Inspect evidence and scope](../../data/phase1_qa.md).")
        text += section("Serving revision / provenance information", table(["Noun", "Serving revision", "Source mode", "Identity strategy"], [(e['noun'], e['current_serving_revision'], e['source_mode'], e['upstream_identity_strategy']) for e in entries]) + "\n[Revision and schema helpers](../../api/data.md) preserve the distinction between a scientific revision and endpoint health.")
        text += section("Important limitations", "\n".join(f"- **{e['noun']}:** {e['limitations']}" for e in entries))
        text += section("Examples using this source", link(page, SOURCE_NOTES.get(source, "vignettes/index.md"), "Source methods, QA plots and examples"))
        pages[page] = text

    verbs = public_verbs()
    verb_index = "# Verbs and callable helpers\n\nAlphabetical reference for the public verb namespace, including compatibility helpers and clearly labeled placeholders. "
    verb_index += "Factories return pipe stages; direct helpers accept data arguments instead. The Usage and Returns sections describe each distinction. `near()` is not implemented.\n\n"
    verb_index += table(["Name", "Meaning"], [(f"[{n}]({n}.md)", summary(f)) for n, f in verbs.items()])
    pages["reference/verbs/index.md"] = verb_index
    for name, func in verbs.items():
        page = f"reference/verbs/{name}.md"
        parts = doc_sections(func)
        note = NOTES.get(name, {})
        contract = note.get("contract", parts.get("Grammar contract", ""))
        text = f"# {name}\n\n{summary(func)}\n"
        if note.get("status"):
            text += f"\n!!! warning \"Availability\"\n    {note['status']}\n"
        text += section("Usage", f"```python\nfrom cubedynamics import verbs as v\nv.{name}{signature(func)}\n```")
        text += section("Arguments", arguments(func))
        text += section("Accepts", note.get("accepts", contract or "Consult the input parameters and implementation notes below. This namespace also includes direct helpers, not only pipe factories."))
        text += section("Returns", note.get("returns", parts.get("Returns", contract or "The public docstring does not specify a return contract. Do not assume a pipe-ready return; consult the linked implementation.")))
        text += section("Order / grammar behavior", note.get("order", contract or "A pipe passes the preceding result to the next callable. Confirm that the previous step's dimensions and semantic state satisfy the input contract. Reductions can remove dimensions; plotting may produce side effects."))
        if name in EXAMPLES:
            example = "Run from the repository root after `python -m pip install -e '.[vignettes]'`. Uses the checked observational PRISM fixture; no network is required.\n\n```python\n" + FIXTURE_SETUP + "\n\n" + EXAMPLES[name] + "\n```"
        else:
            example = note.get("example", "A standalone, reviewed real-data example is not yet available for this helper. See the linked workflow and implementation notes; this reference does not substitute generated observations or invent an executable example.")
        text += section("Minimal example", example)
        text += section("Works with", note.get("accepts", contract or "Use only the input types documented by this callable; not every helper accepts every noun or VirtualCube."))
        related = vignette_links(page, name) + [link(page, "learn/verbs.md", "Learn: verbs"), link(page, "library/index.md", "Noun library"), link(page, "reference/verbs/index.md", "All verbs")]
        if note.get("workflow"):
            related.insert(0, link(page, note['workflow'], "Related workflow"))
        text += section("See also", "\n".join(f"- {item}" for item in related))
        # Some historical docstrings use NumPy headings without underline rows.
        # A second mkdocstrings rendering treats these as plain prose and repeats
        # the complete arguments/returns. Render only the parsed Notes section;
        # the API object pages still use mkdocstrings for full class contracts.
        notes = parts.get("Notes", "No additional implementation notes in the current docstring.")
        source_path = Path(inspect.getsourcefile(func)).resolve().relative_to(ROOT)
        source_line = inspect.getsourcelines(func)[1]
        source_url = f"https://github.com/CU-ESIIL/cubedynamics/blob/main/{source_path}#L{source_line}"
        text += section("Implementation notes", notes + f"\n\n[Implementation source]({source_url}). Signatures and descriptions on this page are generated from this checkout, not hand-maintained copies.")
        pages[page] = text
    return {path: MARKER + text for path, text in pages.items()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    pages = generate()
    stale = [path for path, text in pages.items() if not (DOCS / path).exists() or (DOCS / path).read_text() != text]
    unexpected = [str(p.relative_to(DOCS)) for directory in ("library/nouns", "library/sources", "reference/verbs") for p in (DOCS / directory).glob("*.md") if str(p.relative_to(DOCS)) not in pages]
    if unexpected:
        raise SystemExit(f"Unowned reference pages (review manually): {unexpected}")
    if args.check:
        if stale:
            raise SystemExit("Stale references; run scripts/build_reference_docs.py:\n" + "\n".join(stale))
    else:
        for path, text in pages.items():
            target = DOCS / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
    print(f"{'Checked' if args.check else 'Generated'} {len(pages)} reference pages")


if __name__ == "__main__":
    main()
