#!/usr/bin/env python3
"""Publish the three contained projects' existing certification evidence.

No provider requests. --review records an explicitly performed visual review;
generation never equates image existence with scientific/visual certification.
--check works in a fresh clone without ignored raw upstream samples.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import shutil

from cubedynamics.data.certification import write_live_certification
from cubedynamics.data.lifecycle import CertificationRecord, CertificationOutcome

ROOT=Path(__file__).resolve().parents[1]
RAW=ROOT/"artifacts/source_qa"
ASSETS=ROOT/"docs/assets/generated/source_projects"
PAGE=ROOT/"docs/data/source_projects/evidence.md"
REPORTS={"three_dep":("three_dep/report.json",("three_dep/terrain.png",)),
         "overture":("roads/overture-report.json",("roads/overture.png","roads/comparison.png")),
         "osm":("roads/osm-report.json",("roads/osm.png","roads/comparison.png")),
         "usgs":("usgs/report.json",("usgs/streamflow.png",))}


def digest(path): return hashlib.sha256(path.read_bytes()).hexdigest()


def review(project,note):
    if not note: raise ValueError("Describe the actual review; never auto-approve figures")
    report,figures=REPORTS[project]
    path=RAW/report
    result=json.loads(path.read_text())
    cert=result["certification"]
    if cert["outcome"] not in ("PASS","PASS_WITH_CAVEATS"):
        raise ValueError("Cannot visually approve a failed or blocked retrieval")
    cert["gates"]["visual_qa"]="PASS"
    cert["evidence"]["visual_review"]={"reviewed_at":datetime.now(timezone.utc).isoformat(),
        "scope":"Human-readable figure inspection, not independent ground-truth accuracy",
        "note":note,"figure_sha256":{str(p):digest(RAW/p) for p in figures}}
    validated=CertificationRecord(mode=cert["mode"],outcome=CertificationOutcome(cert["outcome"]),
        gates=cert["gates"],serving_revision=cert["serving_revision"],last_validated=cert["last_validated"],
        evidence=cert["evidence"],caveats=tuple(cert["caveats"]))
    result["certification"]=validated.as_dict()
    write_live_certification(result,path)


def page(reports):
    text=["<!-- Generated by scripts/build_source_project_docs.py; do not edit. -->",
          "# Contained source-project evidence", "",
          "These are bounded experimental proofs, not production source registration or",
          "regional scientific validation. No serving revision has been assigned. Each",
          "row comes from the repository's `CertificationRecord`, not a second registry.", "",
          "| Project / source | Result | Retrieval | Bounded access | Numerical QA | Visual QA |",
          "| --- | --- | --- | --- | --- | --- |"]
    for name,result in reports.items():
        cert=result["certification"]
        gates=cert["gates"]
        text.append(f"| [{name}](../../assets/generated/source_projects/{name}-report.json) | {cert['outcome']} | "
                    + " | ".join(gates.get(k,"NOT_TESTED") for k in ("retrieval","bounded_access","numerical_qa","visual_qa"))+" |")
    text += ["", "The linked JSON records retain exact request URLs, timestamps, transfer evidence,",
             "QA details, schema fingerprints and caveats. Figure review is hash-bound;",
             "changing a figure requires a new review. Live access is an observation at",
             "the recorded time, not a promise about present endpoint health.", "",
             "[3DEP project](three_dep.md) · [Roads project](roads.md) · [USGS streamflow project](usgs.md)", ""]
    return "\n".join(text)


def build():
    ASSETS.mkdir(parents=True,exist_ok=True)
    reports={}
    generated=[]
    for name,(relative,figures) in REPORTS.items():
        result=json.loads((RAW/relative).read_text())
        review=result["certification"]["evidence"].get("visual_review",{})
        for figure in figures:
            if review.get("figure_sha256",{}).get(figure)!=digest(RAW/figure):
                raise ValueError(f"Missing/stale visual review: {name}/{figure}")
            target=ASSETS/Path(figure).name
            shutil.copyfile(RAW/figure,target)
            generated.append(target)
        target=ASSETS/f"{name}-report.json"
        write_live_certification(result,target)
        generated.append(target)
        reports[name]=result
    PAGE.parent.mkdir(parents=True,exist_ok=True)
    PAGE.write_text(page(reports))
    generated.append(PAGE)
    (ASSETS/"manifest.json").write_text(json.dumps({str(p.relative_to(ROOT)):digest(p) for p in generated},indent=2)+"\n")


def check():
    manifest=json.loads((ASSETS/"manifest.json").read_text())
    for file,expected in manifest.items():
        if digest(ROOT/file)!=expected: raise ValueError(f"Stale source-project evidence: {file}")
    reports={name:json.loads((ASSETS/f"{name}-report.json").read_text()) for name in REPORTS}
    if PAGE.read_text()!=page(reports): raise ValueError("Stale generated evidence page")
    for name,result in reports.items():
        cert=result["certification"]
        CertificationRecord(**{**cert,"caveats":tuple(cert["caveats"])})
        for figure,expected in cert["evidence"]["visual_review"]["figure_sha256"].items():
            if digest(ASSETS/Path(figure).name)!=expected: raise ValueError(f"Stale review: {name}")


if __name__=="__main__":
    parser=argparse.ArgumentParser()
    parser.add_argument("--check",action="store_true")
    parser.add_argument("--review",choices=REPORTS)
    parser.add_argument("--note")
    args=parser.parse_args()
    if args.review: review(args.review,args.note)
    elif args.check: check()
    else: build()
    print("Source-project evidence OK")
