#!/usr/bin/env python3
"""Compute release inventories and capture reproducible pre-change checks."""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
import json
import hashlib
import os
from pathlib import Path
import re
import subprocess
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from cubedynamics import __version__, data
from build_reference_docs import public_verbs
from reference_classification import classify

STREAMING = [
    "tests/test_prism_ncss_streaming.py", "tests/test_gridmet_streaming_contract.py",
    "tests/test_global_climate_streaming.py", "tests/test_median_split_synchrony_verb.py",
    "tests/test_spatial_units.py", "tests/test_real_fire_vase_gridmet_smoke.py",
    "src/cubedynamics/tests/test_streaming_contracts.py",
]


def inventory():
    nouns = data.list_sources()
    callables = {name: classify(name, function) for name, function in public_verbs().items()}
    sources = sorted({source for flavors in nouns.values() for source in flavors})
    notebooks = []
    for path in sorted((ROOT / "docs").rglob("*.ipynb")):
        metadata = json.loads(path.read_text())["metadata"]
        if metadata.get("cubedynamics", {}).get("supported_vignette"):
            notebooks.append(str(path.relative_to(ROOT)))
    return {
        "git_sha": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
        "package_version": __version__, "recorded_at": datetime.now(timezone.utc).isoformat(),
        "noun_count": len(nouns), "source_count": len(sources),
        "source_flavor_count": sum(map(len, nouns.values())), "public_callable_count": len(callables),
        "nouns": nouns, "sources": sources, "public_callables": callables,
        "supported_notebooks": notebooks,
        "supported_python_versions": re.findall(r'Programming Language :: Python :: (3\.\d+)"', (ROOT / "pyproject.toml").read_text()),
        "requires_python": re.search(r'requires-python\s*=\s*"([^"]+)"', (ROOT / "pyproject.toml").read_text()).group(1),
        "callable_statuses": {status: sorted(name for name, info in callables.items() if info["status"] == status)
            for status in ("implemented", "compatibility", "deprecated", "placeholder")},
        "generated_reference_pages": sorted(str(p.relative_to(ROOT)) for p in (ROOT / "docs").rglob("*.md")
            if p.read_text().startswith("<!-- Generated by scripts/build_reference_docs.py;")),
    }


def release_manifest(output, reports=(), qa_roots=()):
    """Inventory this checkout; evidence is linked, never inferred from names."""
    result = inventory()
    result["schema_version"] = 1
    result["generated_reference_page_count"] = len(result["generated_reference_pages"])
    result["supported_notebook_count"] = len(result["supported_notebooks"])
    result["test_reports"] = {str(path): junit_counts(path) for path in reports}
    result["qa_artifact_locations"] = [str(path) for path in qa_roots]
    result["certification_records"] = []
    for root in qa_roots:
        for path in sorted(root.rglob("*.json")):
            value = json.loads(path.read_text())
            if "certification" in value:
                result["certification_records"].append({"path": str(path),
                    "source_flavor": value.get("source_flavor"), "certification": value["certification"]})
    result["serving_history"] = json.loads((ROOT / "src/cubedynamics/data/serving_history.json").read_text())
    changed = subprocess.check_output(["git", "diff", "--name-only", "HEAD"], cwd=ROOT, text=True).splitlines()
    untracked = subprocess.check_output(["git", "ls-files", "--others", "--exclude-standard"], cwd=ROOT, text=True).splitlines()
    result["working_tree_changes"] = {name: hashlib.sha256((ROOT / name).read_bytes()).hexdigest()
        if (ROOT / name).is_file() else "deleted" for name in sorted(set(changed + untracked))
        if (ROOT / name).resolve() != output.resolve()}
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    return result


def junit_counts(path):
    suites = ET.parse(path).getroot()
    counts = {key: sum(int(s.get(key, 0)) for s in suites.iter("testsuite"))
              for key in ("tests", "failures", "errors", "skipped")}
    counts["passed"] = counts["tests"] - counts["failures"] - counts["errors"] - counts["skipped"]
    return counts


def baseline(output):
    output.mkdir(parents=True, exist_ok=True)
    destination = output / "baseline.json"
    if destination.exists():
        raise FileExistsError("Refusing to overwrite the pre-change baseline.")
    result = inventory()
    jobs = {
        "offline": ["-m", "pytest", "-m", "not integration and not online", "--maxfail=1", "--disable-warnings", "-q", "--junitxml", str(output / "offline.xml")],
        "streaming": ["-m", "pytest", *STREAMING, "--maxfail=1", "--disable-warnings", "-q", "--junitxml", str(output / "streaming.xml")],
        "source_qa": ["scripts/run_source_qa.py", "--output", str(output / "source_qa")],
        "references": ["scripts/build_reference_docs.py", "--check"],
        "documentation": ["-m", "mkdocs", "build", "--strict", "--site-dir", str(output / "site")],
    }
    def run(item):
        name, args = item
        command = [sys.executable, *args]
        with (output / f"{name}.log").open("w") as stream:
            completed = subprocess.run(command, cwd=ROOT, stdout=stream, stderr=subprocess.STDOUT,
                env={**os.environ, "MPLCONFIGDIR": str(output / "mpl"), "MPLBACKEND": "Agg"})
        entry = {"command": command, "exit_code": completed.returncode, "log": str(output / f"{name}.log")}
        if (output / f"{name}.xml").exists():
            entry["counts"] = junit_counts(output / f"{name}.xml")
        print(f"{name}: exit {completed.returncode}", flush=True)
        return name, entry
    with ThreadPoolExecutor(max_workers=3) as pool:
        result["validation"] = dict(pool.map(run, jobs.items()))
    source_manifest = output / "source_qa" / "manifest.json"
    if source_manifest.exists():
        result["validation"]["source_qa"]["results"] = json.loads(source_manifest.read_text())["reviewed_real_data_results"]
    destination.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(destination)
    return int(any(item["exit_code"] for item in result["validation"].values()))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--baseline", action="store_true")
    mode.add_argument("--manifest", action="store_true")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--test-report", type=Path, action="append", default=[])
    parser.add_argument("--qa-root", type=Path, action="append", default=[])
    args = parser.parse_args()
    if args.baseline:
        raise SystemExit(baseline((args.output or ROOT / "artifacts/source_lifecycle").resolve()))
    destination = args.output or ROOT / "artifacts/release_manifest.json"
    release_manifest(destination, args.test_report, args.qa_root)
    print(destination)
